/** Every page the accessibility checks visit. */
export type Audience = "public" | "customer" | "staff";

export interface PageSpec {
  name: string;
  audience: Audience;
  /** A fixed address, or one built from seeded records (e2e/support/records.ts). */
  path: string | ((r: Record<string, string>) => string);
}

export const PAGES: PageSpec[] = [
  { name: "home", audience: "public", path: "/" },
  { name: "not-found", audience: "public", path: "/no-such-page" },
  { name: "sign-in", audience: "public", path: "/sign-in" },
  { name: "invitation-ended", audience: "public", path: "/invite/no-such-invitation" },
  { name: "staff-sign-in", audience: "public", path: "/admin/sign-in" },
  { name: "staff-invitation-ended", audience: "public", path: "/admin/invite/no-such-invitation" },
  { name: "products", audience: "public", path: "/products" },
  { name: "products-search", audience: "public", path: "/products?q=kingston&sort=name" },
  { name: "category", audience: "public", path: "/categories/networking" },
  { name: "category-filtered", audience: "public", path: "/categories/laptops?f.memory_type=DDR5&b=lenovo" },
  { name: "product", audience: "public", path: (r) => `/products/${r.productSlug}` },
  { name: "compare-empty", audience: "public", path: "/compare" },
  { name: "specials", audience: "public", path: "/specials" },
  { name: "cart-empty", audience: "public", path: "/cart" },
  { name: "order", audience: "public", path: (r) => `/orders/${r.orderNumber}?t=${r.orderToken}&placed=1` },
  { name: "order-on-its-way", audience: "public", path: (r) => `/orders/${r.procuredOrderNumber}?t=${r.procuredOrderToken}` },
  { name: "quote", audience: "public", path: (r) => `/quotes/${r.quoteNumber}?t=${r.quoteToken}` },
  { name: "supplier-rfq", audience: "public", path: (r) => `/supplier/rfq/${r.rfqToken}` },
  { name: "supplier-rfq-wrong", audience: "public", path: "/supplier/rfq/no-such-link" },
  { name: "supplier-po", audience: "public", path: (r) => `/supplier/po/${r.poToken}` },
  { name: "supplier-po-wrong", audience: "public", path: "/supplier/po/no-such-link" },
  { name: "account", audience: "customer", path: "/account" },
  { name: "account-quotes", audience: "customer", path: "/account/quotes" },
  { name: "account-quote-new", audience: "customer", path: "/account/quotes/new" },
  { name: "account-quote", audience: "customer", path: (r) => `/quotes/${r.quoteNumber}` },
  { name: "account-team", audience: "customer", path: "/account/team" },
  { name: "account-sign-in-methods", audience: "customer", path: "/account/sign-in-methods" },
  { name: "account-confirm", audience: "customer", path: "/account/confirm" },
  { name: "account-orders", audience: "customer", path: "/account/orders" },
  { name: "account-business", audience: "customer", path: "/account/business" },
  { name: "account-credit", audience: "customer", path: "/account/credit" },
  { name: "account-orders-open", audience: "customer", path: "/account/orders?state=sent&mine=1" },
  { name: "account-order", audience: "customer", path: (r) => `/orders/${r.portalOrderNumber}` },
  { name: "account-invoices", audience: "customer", path: "/account/invoices" },
  { name: "account-invoices-open", audience: "customer", path: "/account/invoices?show=open" },
  { name: "account-statement", audience: "customer", path: "/account/statement" },
  { name: "account-payments", audience: "customer", path: "/account/payments" },
  { name: "account-deliveries", audience: "customer", path: "/account/deliveries" },
  { name: "account-returns", audience: "customer", path: "/account/returns" },
  { name: "account-return", audience: "customer", path: (r) => `/account/returns/${r.portalReturnNumber}` },
  { name: "account-return-new", audience: "customer", path: (r) => `/account/returns/new?order=${r.portalOrderNumber}` },
  { name: "account-return-repair", audience: "customer", path: "/account/returns/RMA-TEST2" },
  { name: "account-warranty", audience: "customer", path: "/account/warranty" },
  { name: "account-warranty-search", audience: "customer", path: "/account/warranty?q=nothing-like-this" },
  { name: "order-trade", audience: "customer", path: (r) => `/orders/${r.portalOrderNumber}` },
  { name: "account-lists", audience: "customer", path: "/account/lists" },
  { name: "account-list", audience: "customer", path: (r) => `/account/lists/${r.portalList}` },
  { name: "cart-trade", audience: "customer", path: "/cart" },
  { name: "product-trade", audience: "customer", path: (r) => `/products/${r.productSlug}` },
  { name: "products-trade", audience: "customer", path: "/products" },
  { name: "admin-overview", audience: "staff", path: "/admin" },
  { name: "admin-customers", audience: "staff", path: "/admin/customers" },
  { name: "admin-customers-waiting", audience: "staff", path: "/admin/customers?check=waiting" },
  { name: "admin-customer", audience: "staff", path: (r) => `/admin/customers/${r.business}` },
  { name: "admin-credit", audience: "staff", path: "/admin/credit" },
  { name: "admin-price-levels", audience: "staff", path: "/admin/customer-types" },
  { name: "admin-markets", audience: "staff", path: "/admin/markets" },
  { name: "admin-market", audience: "staff", path: "/admin/markets/bw" },
  { name: "admin-market-new", audience: "staff", path: "/admin/markets/new" },
  { name: "admin-products", audience: "staff", path: "/admin/products" },
  { name: "admin-product-new", audience: "staff", path: "/admin/products/new" },
  { name: "admin-product", audience: "staff", path: (r) => `/admin/products/${r.product}` },
  { name: "admin-categories", audience: "staff", path: "/admin/categories" },
  { name: "admin-category", audience: "staff", path: (r) => `/admin/categories/${r.category}` },
  { name: "admin-suppliers", audience: "staff", path: "/admin/suppliers" },
  { name: "admin-supplier-new", audience: "staff", path: "/admin/suppliers/new" },
  { name: "admin-supplier", audience: "staff", path: (r) => `/admin/suppliers/${r.supplier}` },
  { name: "admin-price-list-columns", audience: "staff", path: (r) => `/admin/suppliers/${r.supplier}/imports/${r.columnsImport}` },
  { name: "admin-price-list-review", audience: "staff", path: (r) => `/admin/suppliers/${r.supplier}/imports/${r.readyImport}` },
  { name: "admin-sourcing", audience: "staff", path: "/admin/sourcing" },
  { name: "admin-exchange-rates", audience: "staff", path: "/admin/exchange-rates" },
  { name: "admin-specials", audience: "staff", path: "/admin/specials" },
  { name: "admin-special-new", audience: "staff", path: "/admin/specials/new" },
  { name: "admin-special", audience: "staff", path: (r) => `/admin/specials/${r.special}` },
  { name: "admin-consignment", audience: "staff", path: "/admin/specials/consignment" },
  { name: "admin-shop", audience: "staff", path: "/admin/shop" },
  { name: "admin-orders", audience: "staff", path: "/admin/orders" },
  { name: "admin-order", audience: "staff", path: (r) => `/admin/orders/${r.order}` },
  { name: "admin-quotes", audience: "staff", path: "/admin/quotes" },
  { name: "admin-quote", audience: "staff", path: (r) => `/admin/quotes/${r.quote}` },
  { name: "admin-quote-rules", audience: "staff", path: "/admin/quotes/rules" },
  { name: "admin-quote-report", audience: "staff", path: "/admin/quotes/report" },
  { name: "admin-purchase-orders", audience: "staff", path: "/admin/purchase-orders" },
  { name: "admin-purchase-order", audience: "staff", path: (r) => `/admin/purchase-orders/${r.waitingPo}` },
  { name: "admin-purchase-order-sent", audience: "staff", path: (r) => `/admin/purchase-orders/${r.sentPo}` },
  { name: "admin-purchase-order-rules", audience: "staff", path: "/admin/purchase-orders/rules" },
  { name: "admin-order-procured", audience: "staff", path: (r) => `/admin/orders/${r.procuredOrder}` },
  { name: "admin-shipments", audience: "staff", path: "/admin/logistics" },
  { name: "admin-shipment-new", audience: "staff", path: "/admin/logistics/shipments/new?source=LIVE" },
  { name: "admin-shipment-live", audience: "staff", path: (r) => `/admin/logistics/shipments/${r.liveShipment}` },
  { name: "admin-shipment-past", audience: "staff", path: (r) => `/admin/logistics/shipments/${r.pastShipment}` },
  { name: "admin-shipments-import", audience: "staff", path: "/admin/logistics/import" },
  { name: "admin-freight-estimates", audience: "staff", path: "/admin/logistics/estimates?origin=ZA&mode=ROAD&kg=25&m3=0.1&value=1000" },
  { name: "admin-duty", audience: "staff", path: "/admin/logistics/duty" },
  { name: "admin-logistics-rules", audience: "staff", path: "/admin/logistics/rules" },
  { name: "admin-stock", audience: "staff", path: "/admin/stock" },
  { name: "admin-deliveries", audience: "staff", path: "/admin/deliveries" },
  { name: "admin-returns", audience: "staff", path: "/admin/returns" },
  { name: "admin-return", audience: "staff", path: (r) => `/admin/returns/${r.portalReturn}` },
  { name: "admin-order-portal", audience: "staff", path: (r) => `/admin/orders/${r.portalOrder}` },
  { name: "admin-return-settle", audience: "staff", path: (r) => `/admin/returns/${r.aftersalesReturn}` },
  { name: "admin-warranty", audience: "staff", path: "/admin/warranty" },
  { name: "admin-warranty-search", audience: "staff", path: "/admin/warranty?q=demo sn 0002" },
  { name: "admin-staff", audience: "staff", path: "/admin/staff" },
  { name: "admin-audit", audience: "staff", path: "/admin/audit" },
  { name: "admin-account", audience: "staff", path: "/admin/account" },
  { name: "admin-confirm", audience: "staff", path: "/admin/confirm" },
];
